version: "3.7"

services:
  db:
    image: postgres:15.1
    restart: unless-stopped
    container_name: taxi_service_db
    environment:
        POSTGRES_DB: taxi_service
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
